application: etchcode
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.well-known
  static_dir: .well-known/
  
- url: /static
  static_dir: static/
  
- url: /bower_components
  static_dir: bower_components/

- url: /api/.+
  script: api.app

- url: /(.*)
  static_files: static/pages/index.html
  upload: static\/pages\/index.html

libraries:
- name: webapp2
  version: "2.5.2"
