application: etchcode
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.well-known/acme-challenge/rNd4bawGtFjt-vOsJEjXePBqg7YrvwOG7nMXiqkIxoE
  static_files: letsencrypt_key.txt
  upload: letsencrypt_key.txt
  mime_type: text/plain
  
- url: /static
  static_dir: static/
  
- url: /bower_components
  static_dir: bower_components/

- url: /api/.+
  script: api.app

- url: /
  static_files: static/pages/index.html
  upload: static\/pages\/index.html

libraries:
- name: webapp2
  version: "2.5.2"
