application: etchcode
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static/pages/index.html
  upload: static\/pages\/index.html
 
- url: /static
  static_dir: static/

- url: /api/.+
  script: api.app

libraries:
- name: webapp2
  version: "2.5.2"
