application: etchcode
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /editor
  static_files: static/editor/index.html
  upload: static\/editor\/index.html

- url: /static/(.*)
  static_files: static/\1
  upload: static\/\1

- url: /api/.+
  script: api.app

libraries:
- name: webapp2
  version: "2.5.2"
